version: '3.8'
services:
  # MySQL Database Service
  mysql_db:
    image: mysql:8.0
    container_name: warehouse_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: warehouse_management
      MYSQL_USER: root
      MYSQL_PASSWORD: root-pw
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"  # Use 3307 to avoid conflicts with local MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10

  # Flask API Service
  flask_api:
    container_name: flask_api
    restart: always
    env_file: .env
    build: .
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_ENGINE=mysql+pymysql
      - DB_HOST=mysql_db
      - DB_NAME=warehouse_management
      - DB_USERNAME=root
      - DB_PASS=root-pw
      - DB_PORT=3306
    networks:
      - db_network
      - web_network

  # Nginx Reverse Proxy
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5001:5001"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - flask_api

  # Optional: PHPMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: warehouse_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password_123
      MYSQL_ROOT_PASSWORD: root_password_123
    ports:
      - "8080:80"
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local